/* eslint-env mocha */
/* eslint-disable max-nested-callbacks, max-statements, no-magic-numbers, no-unused-expressions */
/* eslint-disable @typescript-eslint/no-var-requires, global-require */
import { expect } from "chai";
import * as sinon from "sinon";
import * as Fs from "fs";
import * as Path from "path";
import { logger } from "@xarc/dev-base";
import * as loadXarcOptionsModule from "../../../src/util/load-xarc-options";
import * as injectEntryModule from "../../../src/util/inject-entry";

const mkdirp = require("mkdirp");

const entryModulePath = require.resolve("../../../src/partials/entry");
const jsonpCdn = require.resolve("../../../src/client/webpack5-jsonp-cdn");
const autogeneratedText = "// Do not modify - electrode auto-generated.";

const fixtureCwd = Path.resolve(__dirname, "../../fixtures/entry-config");
const badFixtureCwd = Path.resolve(__dirname, "../../fixtures/entry-config-bad");
const appCwd = Path.resolve("/fake/app");

type WriteCall = { file: string; content: string };

describe("partials/entry makeEntryPartial", () => {
  let xarcOptions: any;
  let existsSyncStub: sinon.SinonStub;
  let writeFileSyncStub: sinon.SinonStub;
  let mkdirpSyncStub: sinon.SinonStub;
  let injectEntryStub: sinon.SinonStub;
  let loggerInfoStub: sinon.SinonStub;
  let savedWebpackDev: string | undefined;

  const makeXarcOptions = (overrides: any = {}) =>
    Object.assign(
      {
        cwd: appCwd,
        AppMode: {
          src: { dir: "src", client: "src/client" },
          subApps: {}
        },
        options: {},
        webpack: {},
        babel: {
          envTargets: { default: {}, node: {} },
          target: "default"
        }
      },
      overrides
    );

  const run = () => {
    const makeEntryPartial = require(entryModulePath);
    return makeEntryPartial();
  };

  const writes = (): WriteCall[] =>
    writeFileSyncStub.args.map(([file, content]) => ({ file, content }));

  const findWrite = (baseName: string): WriteCall => {
    const found = writes().find(w => Path.basename(w.file) === baseName);
    expect(found, `expected a write of ${baseName}`).to.exist;
    return found;
  };

  beforeEach(() => {
    savedWebpackDev = process.env.WEBPACK_DEV;
    delete process.env.WEBPACK_DEV;

    xarcOptions = makeXarcOptions();
    sinon.stub(loadXarcOptionsModule, "loadXarcOptions").callsFake(() => xarcOptions);
    injectEntryStub = sinon.stub(injectEntryModule, "injectEntry").callThrough();
    existsSyncStub = sinon.stub(Fs, "existsSync").returns(false);
    writeFileSyncStub = sinon.stub(Fs, "writeFileSync");
    mkdirpSyncStub = sinon.stub(mkdirp, "sync");
    loggerInfoStub = sinon.stub(logger, "info");
  });

  afterEach(() => {
    sinon.restore();
    delete require.cache[entryModulePath];
    if (savedWebpackDev === undefined) {
      delete process.env.WEBPACK_DEV;
    } else {
      process.env.WEBPACK_DEV = savedWebpackDev;
    }
  });

  describe("searchEntryConfig", () => {
    it("uses entry.config.js from the client dir when present", () => {
      xarcOptions = makeXarcOptions({ cwd: fixtureCwd });

      const partial = run();

      expect(partial.context).to.equal(Path.join(fixtureCwd, "src/client"));
      expect(partial.entry).to.deep.equal({ main: [jsonpCdn, "./custom-main.js"] });
      expect(loggerInfoStub).to.have.been.calledWithMatch(/Using custom entry config from/);
      expect(mkdirpSyncStub).to.not.have.been.called;
      expect(writeFileSyncStub).to.not.have.been.called;
    });

    it("logs an error and exits when entry.config.js fails to load", () => {
      xarcOptions = makeXarcOptions({ cwd: badFixtureCwd });
      const exitStub = sinon.stub(process, "exit");
      const loggerErrorStub = sinon.stub(logger, "error");

      const partial = run();

      expect(exitStub).to.have.been.calledWith(1);
      expect(loggerErrorStub).to.have.been.calledWithMatch(/entry\.config\.js failed/);
      expect(loggerInfoStub).to.not.have.been.calledWithMatch(/Using custom entry config from/);
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
    });
  });

  describe("single app entry", () => {
    it("skips subapp search when options.subapp is false", () => {
      xarcOptions = makeXarcOptions({
        options: { subapp: false },
        AppMode: {
          src: { dir: "src", client: "src/client" },
          subApps: { Home: { name: "Home", subAppDir: "home", entry: "subapp-home.js" } }
        }
      });
      existsSyncStub.withArgs(Path.join(appCwd, "src/client", "./app.js")).returns(true);

      const partial = run();

      expect(loggerInfoStub).to.have.been.calledWithMatch(/subapp turned off/);
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.js"]);
      expect(mkdirpSyncStub).to.not.have.been.called;
    });

    it("finds app.tsx under partial.context", () => {
      existsSyncStub.withArgs(Path.join(appCwd, "src/client", "./app.tsx")).returns(true);

      const partial = run();

      expect(partial.context).to.equal(Path.join(appCwd, "src/client"));
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.tsx"]);
      expect(loggerInfoStub).to.have.been.calledWithMatch(/Default to single app entry point/);
    });

    it("falls back to AppMode.src.dir and moves context there", () => {
      existsSyncStub.withArgs(Path.join("src", "./app.jsx")).returns(true);

      const partial = run();

      expect(partial.context).to.equal(Path.join(appCwd, "src"));
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
      expect(loggerInfoStub).to.have.been.calledWithMatch(/setting webpack context to it/);
    });

    it("assumes ./app.jsx when no entry file exists", () => {
      const partial = run();

      expect(partial.context).to.equal(Path.join(appCwd, "src/client"));
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
      expect(loggerInfoStub).to.have.been.calledWithMatch(/Unable to determine your app's entry/);
    });

    it("falls through to single entry when subApps is empty", () => {
      xarcOptions.AppMode.subApps = {};

      const partial = run();

      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
      expect(loggerInfoStub).to.not.have.been.calledWithMatch(/Found version 1 subapps/);
    });
  });

  describe("subapps in dev mode (WEBPACK_DEV set)", () => {
    const hmrDir = Path.resolve(appCwd, "src", ".__dev_hmr");

    beforeEach(() => {
      process.env.WEBPACK_DEV = "true";
    });

    it("generates HMR entries and writes .gitignore", () => {
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "Sub/Home", entry: "subapp-home.js" }
      };

      const partial = run();

      expect(loggerInfoStub).to.have.been.calledWithMatch(/Found version 1 subapps: Home/);
      expect(partial.context).to.equal(Path.resolve(appCwd, "src"));
      expect(partial.entry).to.deep.equal({ home: ["./.__dev_hmr/hmr-sub-home.js"] });

      expect(mkdirpSyncStub).to.have.been.calledWith(hmrDir);
      const gitIgnore = findWrite(".gitignore");
      expect(gitIgnore.file).to.equal(Path.join(hmrDir, ".gitignore"));
      expect(gitIgnore.content).to.contain("Electrode default hot module loaders");

      const hmr = findWrite("hmr-sub-home.js");
      expect(hmr.file).to.equal(Path.join(hmrDir, "hmr-sub-home.js"));
      expect(hmr.content).to.contain(autogeneratedText);
      expect(hmr.content).to.contain(`import subApp from "../Sub/Home/subapp-home.js";`);
      expect(hmr.content).to.contain(`module.hot.accept("../Sub/Home/subapp-home.js"`);
      expect(hmr.content).to.contain(`require("subapp-web").hotReloadSubApp`);
      expect(hmr.content).to.not.contain("subapp-redux");
    });

    it("does not rewrite .gitignore when it already exists", () => {
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "home", entry: "subapp-home.js" }
      };
      existsSyncStub.withArgs(Path.join(hmrDir, ".gitignore")).returns(true);

      run();

      expect(writes().map(w => Path.basename(w.file))).to.deep.equal(["hmr-home.js"]);
    });

    it("includes reducer HMR code when manifest has reducers", () => {
      xarcOptions.AppMode.subApps = {
        Shop: { name: "Shop", subAppDir: "shop", entry: "subapp-shop.js", reducers: true }
      };

      const partial = run();

      expect(partial.entry).to.deep.equal({ shop: ["./.__dev_hmr/hmr-shop.js"] });
      const hmr = findWrite("hmr-shop.js");
      expect(hmr.content).to.contain(`import("subapp-redux")`);
      expect(hmr.content).to.contain(`import("../shop/reducers")`);
      expect(hmr.content).to.contain(`module.hot.accept("../shop/reducers", replaceReducer)`);
    });

    it("returns the subapp entry directly when manifest.hmrSelfAccept is set", () => {
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "home", entry: "subapp-home.js", hmrSelfAccept: true }
      };

      const partial = run();

      expect(partial.entry).to.deep.equal({ home: ["./home/subapp-home.js"] });
      expect(writes().map(w => Path.basename(w.file))).to.deep.equal([".gitignore"]);
    });

    it("uses module entry as-is when manifest.module is set", () => {
      xarcOptions.AppMode.subApps = {
        Pkg: {
          name: "Pkg",
          subAppDir: "pkg",
          module: true,
          entry: "@scope/pkg-subapp",
          reducers: "@scope/pkg-subapp/reducers"
        },
        PkgSelf: {
          name: "PkgSelf",
          subAppDir: "pkg-self",
          module: true,
          entry: "@scope/pkg-self",
          hmrSelfAccept: true
        }
      };

      const partial = run();

      expect(partial.entry).to.deep.equal({
        pkg: ["./.__dev_hmr/hmr-pkg.js"],
        pkgself: ["@scope/pkg-self"]
      });
      const hmr = findWrite("hmr-pkg.js");
      expect(hmr.content).to.contain(`import subApp from "@scope/pkg-subapp";`);
      expect(hmr.content).to.contain(`import("@scope/pkg-subapp/reducers")`);
    });

    it("generates standalone MFE HMR entry with lowercased dashed chunk name", () => {
      xarcOptions.mfeOptions = { MFE_STANDALONE_ENABLED: true };
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "Sub\\Home", entry: "Entry/Sub-App.js" }
      };

      const partial = run();

      expect(partial.entry).to.deep.equal({ home: ["./.__dev_hmr/hmr-sub-home.js"] });
      const hmr = findWrite("hmr-sub-home.js");
      expect(hmr.content).to.contain(`/* webpackChunkName: "entry-sub-app.js" */`);
      expect(hmr.content).to.contain(`import(/* webpackChunkName: "entry-sub-app.js" */ "../Sub\\Home/Entry/Sub-App.js")`);
      expect(hmr.content).to.contain("const refreshApp = (info) =>");
      expect(hmr.content).to.contain("window.xarcV1.getSubApp(info.name)");
      expect(hmr.content).to.not.contain("hotReloadSubApp");
      expect(hmr.content).to.not.contain("subapp-redux");
    });

    it("generates standalone MFE HMR entry with reducers", () => {
      xarcOptions.mfeOptions = { MFE_STANDALONE_ENABLED: true };
      xarcOptions.AppMode.subApps = {
        Shop: { name: "Shop", subAppDir: "shop", entry: "subapp-shop.js", reducers: true }
      };

      run();

      const hmr = findWrite("hmr-shop.js");
      expect(hmr.content).to.contain(`import(/* webpackChunkName: "subapp-shop.js" */ "../shop/subapp-shop.js")`);
      expect(hmr.content).to.contain(`import("subapp-redux")`);
      expect(hmr.content).to.contain("const refreshApp = (info) =>");
    });

    it("treats MFE_STANDALONE_ENABLED false as the non-standalone path", () => {
      xarcOptions.mfeOptions = { MFE_STANDALONE_ENABLED: false };
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "home", entry: "subapp-home.js" }
      };

      run();

      const hmr = findWrite("hmr-home.js");
      expect(hmr.content).to.contain(`import subApp from "../home/subapp-home.js";`);
      expect(hmr.content).to.not.contain("webpackChunkName");
    });
  });

  describe("subapps in prod mode (WEBPACK_DEV unset)", () => {
    const prodDir = Path.resolve(appCwd, "src", ".__prod__");

    it("writes prod entries with require and injects jsonp cdn", () => {
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "Sub/Home", entry: "subapp-home.js" },
        Shop: { name: "Shop", subAppDir: "Sub\\Shop", entry: "subapp-shop.js" }
      };

      const partial = run();

      expect(mkdirpSyncStub).to.have.been.calledWith(prodDir);
      expect(writes().some(w => Path.basename(w.file) === ".gitignore")).to.equal(false);
      expect(partial.entry).to.deep.equal({
        home: [jsonpCdn, "./.__prod__/prod-sub-home.js"],
        shop: [jsonpCdn, "./.__prod__/prod-sub-shop.js"]
      });

      const home = findWrite("prod-sub-home.js");
      expect(home.file).to.equal(Path.join(prodDir, "prod-sub-home.js"));
      expect(home.content).to.contain(autogeneratedText);
      expect(home.content).to.contain(`const subApp = require("Sub/Home/subapp-home.js");`);
      expect(home.content).to.contain("export default subApp;");
      expect(home.content).to.not.contain("webpackChunkName");

      const shop = findWrite("prod-sub-shop.js");
      expect(shop.content).to.contain(`require("Sub\\Shop/subapp-shop.js")`);
    });

    it("writes standalone MFE prod entries with dynamic import and bootstrap chunk name", () => {
      xarcOptions.mfeOptions = { MFE_STANDALONE_ENABLED: true };
      xarcOptions.AppMode.subApps = {
        Cart: { name: "Shop/Cart", subAppDir: "shop/cart", entry: "subapp-cart.js" },
        Pkg: { name: "Pkg", subAppDir: "pkg", module: true, entry: "@scope/pkg-subapp" }
      };

      const partial = run();

      expect(partial.entry).to.deep.equal({
        "shop/cart": [jsonpCdn, "./.__prod__/prod-shop-cart.js"],
        pkg: [jsonpCdn, "./.__prod__/prod-pkg.js"]
      });

      const cart = findWrite("prod-shop-cart.js");
      expect(cart.content).to.contain(
        `import(/* webpackChunkName: "shop-cart~.bootstrap" */ "shop/cart/subapp-cart.js")`
      );
      const pkg = findWrite("prod-pkg.js");
      expect(pkg.content).to.contain(`import(/* webpackChunkName: "pkg~.bootstrap" */ "@scope/pkg-subapp")`);
    });

    it("treats MFE_STANDALONE_ENABLED false as the require path", () => {
      xarcOptions.mfeOptions = { MFE_STANDALONE_ENABLED: false };
      xarcOptions.AppMode.subApps = {
        Home: { name: "Home", subAppDir: "home", entry: "subapp-home.js" }
      };

      run();

      const home = findWrite("prod-home.js");
      expect(home.content).to.contain(`require("home/subapp-home.js")`);
    });
  });

  describe("shouldPolyfill", () => {
    const polyfills = ["core-js", "regenerator-runtime/runtime"];

    it("does not inject polyfills when enableBabelPolyfill is off", () => {
      const partial = run();

      expect(injectEntryStub).to.have.been.calledOnce;
      expect(injectEntryStub.firstCall.args[1]).to.equal(jsonpCdn);
      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
    });

    it("injects polyfills when enabled with only default,node targets", () => {
      xarcOptions.webpack.enableBabelPolyfill = true;

      const partial = run();

      expect(injectEntryStub.firstCall.args[1]).to.deep.equal([jsonpCdn, ...polyfills]);
      expect(partial.entry).to.deep.equal([jsonpCdn, ...polyfills, "./app.jsx"]);
    });

    it("injects polyfills for multiple targets when babel.target is default", () => {
      xarcOptions.webpack.enableBabelPolyfill = true;
      xarcOptions.babel.envTargets = { default: {}, node: {}, modern: {} };
      xarcOptions.babel.target = "default";

      const partial = run();

      expect(partial.entry).to.deep.equal([jsonpCdn, ...polyfills, "./app.jsx"]);
    });

    it("skips polyfills for multiple targets when babel.target is not default", () => {
      xarcOptions.webpack.enableBabelPolyfill = true;
      xarcOptions.babel.envTargets = { default: {}, node: {}, modern: {} };
      xarcOptions.babel.target = "modern";

      const partial = run();

      expect(partial.entry).to.deep.equal([jsonpCdn, "./app.jsx"]);
    });

    it("omits jsonp cdn in dev mode but still injects polyfills", () => {
      process.env.WEBPACK_DEV = "true";
      xarcOptions.webpack.enableBabelPolyfill = true;

      const partial = run();

      expect(partial.entry).to.deep.equal([...polyfills, "./app.jsx"]);
    });
  });
});
